"""add missing columns to chat_sessions

Revision ID: 008a612b804d
Revises: 11939f418bd8
Create Date: 2025-05-22 05:31:30.923919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '008a612b804d'
down_revision: Union[str, None] = '11939f418bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('status', sa.String(length=32), nullable=True))
    op.add_column('chat_sessions', sa.Column('session_metadata', sa.JSON(), nullable=True))
    op.add_column('chat_sessions', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'completed_at')
    op.drop_column('chat_sessions', 'session_metadata')
    op.drop_column('chat_sessions', 'status')
    # ### end Alembic commands ###
