"""add_enhanced_chat_configuration_tables

Revision ID: 690b6b1f1213
Revises: b84fe9c40388
Create Date: 2025-06-16 11:22:07.407975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '690b6b1f1213'
down_revision: Union[str, None] = 'b84fe9c40388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_invites_email', table_name='invites')
    op.drop_table('invites')
    op.drop_index('idx_appointments_clinician_id', table_name='appointments')
    op.drop_index('idx_appointments_patient_id', table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('eligibility_results')
    op.drop_index('idx_chat_sessions_patient_id', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('idx_lab_orders_patient_id', table_name='lab_orders')
    op.drop_table('lab_orders')
    op.drop_table('chat_questions')
    op.drop_index('idx_chat_answers_session_id', table_name='chat_answers')
    op.drop_table('chat_answers')
    op.drop_table('recurring_availability')
    op.drop_table('accounts')
    op.drop_index('idx_patients_clinician_id', table_name='patients')
    op.drop_index('idx_patients_external_id', table_name='patients')
    op.drop_index('idx_patients_user_id', table_name='patients')
    op.drop_table('patients')
    op.drop_table('risk_assessments')
    op.drop_index('idx_lab_results_order_id', table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index('idx_users_account_id', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('patient', 'clinician', 'admin', 'super_admin', 'lab_tech', name='user_role'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'inactive', 'invited', 'suspended', name='user_status'), server_default=sa.text("'active'::user_status"), autoincrement=False, nullable=False),
    sa.Column('clinician_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='users_account_id_fkey'),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], name='users_clinician_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_account_id', 'users', ['account_id'], unique=False)
    op.create_table('lab_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('lab_api_result_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'available', 'reviewed', name='lab_result_status'), server_default=sa.text("'pending'::lab_result_status"), autoincrement=False, nullable=False),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['lab_orders.id'], name='lab_results_order_id_fkey'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name='lab_results_reviewed_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='lab_results_pkey')
    )
    op.create_index('idx_lab_results_order_id', 'lab_results', ['order_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('risk_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recommendations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='risk_assessments_patient_id_fkey'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name='risk_assessments_session_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='risk_assessments_pkey')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('clinician_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'inactive', 'archived', name='patient_status'), server_default=sa.text("'active'::patient_status"), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('emergency_contact_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('emergency_contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='patients_account_id_fkey'),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], name='patients_clinician_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='patients_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='patients_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_patients_user_id', 'patients', ['user_id'], unique=False)
    op.create_index('idx_patients_external_id', 'patients', ['external_id'], unique=False)
    op.create_index('idx_patients_clinician_id', 'patients', ['clinician_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'inactive', 'suspended', name='account_status'), server_default=sa.text("'active'::account_status"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='accounts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('recurring_availability',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('clinician_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('days_of_week', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('time_slots', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], name='recurring_availability_clinician_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='recurring_availability_pkey')
    )
    op.create_table('chat_answers',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['chat_questions.id'], name='chat_answers_question_id_fkey'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name='chat_answers_session_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_answers_pkey')
    )
    op.create_index('idx_chat_answers_session_id', 'chat_answers', ['session_id'], unique=False)
    op.create_table('chat_questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('next_question_logic', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='chat_questions_pkey')
    )
    op.create_table('lab_orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('eligibility_result_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('lab_api_order_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('ordered', 'processing', 'completed', 'cancelled', name='lab_order_status'), server_default=sa.text("'ordered'::lab_order_status"), autoincrement=False, nullable=False),
    sa.Column('ordered_tests', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('insurance_information', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['eligibility_result_id'], ['eligibility_results.id'], name='lab_orders_eligibility_result_id_fkey'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='lab_orders_patient_id_fkey'),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name='lab_orders_provider_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='lab_orders_pkey')
    )
    op.create_index('idx_lab_orders_patient_id', 'lab_orders', ['patient_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('clinician_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('in_progress', 'completed', 'abandoned', name='chat_session_status'), server_default=sa.text("'in_progress'::chat_session_status"), autoincrement=False, nullable=False),
    sa.Column('session_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], name='chat_sessions_clinician_id_fkey'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='chat_sessions_patient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_chat_sessions_patient_id', 'chat_sessions', ['patient_id'], unique=False)
    op.create_table('eligibility_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_eligible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='eligibility_results_patient_id_fkey'),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name='eligibility_results_provider_id_fkey'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name='eligibility_results_session_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='eligibility_results_pkey')
    )
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('appointment_type', postgresql.ENUM('virtual', 'in_person', name='appointment_type'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('scheduled', 'completed', 'cancelled', 'no_show', name='appointment_status'), server_default=sa.text("'scheduled'::appointment_status"), autoincrement=False, nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('confirmation_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('clinician_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='appointments_patient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='appointments_pkey')
    )
    op.create_index('idx_appointments_patient_id', 'appointments', ['patient_id'], unique=False)
    op.create_index('idx_appointments_clinician_id', 'appointments', ['clinician_id'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'completed', 'expired', name='invite_status'), server_default=sa.text("'pending'::invite_status"), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('invite_token', sa.VARCHAR(length=255), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('clinician_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('custom_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('accepted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='invites_patient_id_fkey'),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name='invites_provider_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invites_pkey'),
    sa.UniqueConstraint('invite_token', name='unique_invite_token', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_invites_email', 'invites', ['email'], unique=False)
    # ### end Alembic commands ###
