"""Add source_type and access_level to knowledge_sources

Revision ID: 91322dac4cb2
Revises: b2d62cbf263a
Create Date: 2025-07-05 00:21:51.940575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91322dac4cb2'
down_revision: Union[str, None] = 'b2d62cbf263a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_chat_sessions_patient_id'), table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_started_at'), table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_status'), table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_strategy_id'), table_name='ai_chat_sessions')
    op.drop_table('ai_chat_sessions')
    op.drop_table('knowledge_sources')
    op.drop_table('accounts')
    op.drop_table('strategy_knowledge_sources')
    op.drop_table('lab_orders')
    op.drop_table('chat_strategies')
    op.drop_table('targeting_rules')
    op.drop_index(op.f('ix_ai_chat_messages_created_at'), table_name='ai_chat_messages')
    op.drop_index(op.f('ix_ai_chat_messages_role'), table_name='ai_chat_messages')
    op.drop_index(op.f('ix_ai_chat_messages_session_id'), table_name='ai_chat_messages')
    op.drop_table('ai_chat_messages')
    op.drop_table('lab_results')
    op.drop_index(op.f('idx_invites_email'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_ai_session_analytics_session_id'), table_name='ai_session_analytics')
    op.drop_table('ai_session_analytics')
    op.drop_table('risk_assessments')
    op.drop_table('patients')
    op.drop_index(op.f('ix_ai_extraction_rules_entity_type'), table_name='ai_extraction_rules')
    op.drop_index(op.f('ix_ai_extraction_rules_strategy_id'), table_name='ai_extraction_rules')
    op.drop_table('ai_extraction_rules')
    op.drop_index(op.f('idx_document_chunks_embedding'), table_name='document_chunks', postgresql_using='ivfflat')
    op.drop_index(op.f('idx_document_chunks_knowledge_source'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_table('eligibility_results')
    op.drop_table('users')
    op.drop_table('outcome_actions')
    op.drop_index(op.f('idx_appointments_clinician'), table_name='appointments')
    op.drop_index(op.f('idx_appointments_date'), table_name='appointments')
    op.drop_index(op.f('idx_appointments_patient'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('strategy_executions')
    op.drop_table('strategy_analytics')
    op.drop_index(op.f('idx_clinician_availability_date'), table_name='clinician_availability')
    op.drop_table('clinician_availability')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinician_availability',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clinician_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('time_slot', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('available', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('clinician_availability_pkey'))
    )
    op.create_index(op.f('idx_clinician_availability_date'), 'clinician_availability', ['clinician_id', 'date'], unique=False)
    op.create_table('strategy_analytics',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('strategy_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('patients_screened', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('criteria_met', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('criteria_not_met', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('incomplete_data', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('avg_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tasks_created', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('charts_flagged', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('messages_sent', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('followups_scheduled', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['chat_strategies.id'], name=op.f('strategy_analytics_strategy_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('strategy_analytics_pkey')),
    sa.UniqueConstraint('strategy_id', 'date', name=op.f('strategy_analytics_strategy_id_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('strategy_executions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('strategy_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('patient_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('triggered_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('trigger_criteria', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('execution_status', sa.VARCHAR(), server_default=sa.text("'in_progress'::character varying"), autoincrement=False, nullable=False),
    sa.Column('outcome_result', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('executed_actions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('strategy_executions_patient_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['ai_chat_sessions.id'], name=op.f('strategy_executions_session_id_fkey')),
    sa.ForeignKeyConstraint(['strategy_id'], ['chat_strategies.id'], name=op.f('strategy_executions_strategy_id_fkey')),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name=op.f('strategy_executions_triggered_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('strategy_executions_pkey'))
    )
    op.create_table('appointments',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('clinician_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('appointment_type', postgresql.ENUM('virtual', 'in-person', name='appointment_type'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('scheduled', 'completed', 'canceled', 'rescheduled', name='appointment_status'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confirmation_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], name=op.f('appointments_clinician_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('appointments_patient_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('appointments_pkey'))
    )
    op.create_index(op.f('idx_appointments_patient'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('idx_appointments_date'), 'appointments', ['date_time'], unique=False)
    op.create_index(op.f('idx_appointments_clinician'), 'appointments', ['clinician_id'], unique=False)
    op.create_table('outcome_actions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('strategy_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('sequence', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['chat_strategies.id'], name=op.f('outcome_actions_strategy_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('outcome_actions_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('clinician_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('eligibility_results',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('eligibility_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('criteria_met', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('assessed_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], name=op.f('eligibility_results_assessed_by_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('eligibility_results_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('eligibility_results_pkey'))
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('knowledge_source_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['knowledge_source_id'], ['knowledge_sources.id'], name=op.f('document_chunks_knowledge_source_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('document_chunks_pkey'))
    )
    op.create_index(op.f('idx_document_chunks_knowledge_source'), 'document_chunks', ['knowledge_source_id'], unique=False)
    op.create_index(op.f('idx_document_chunks_embedding'), 'document_chunks', ['embedding'], unique=False, postgresql_using='ivfflat')
    op.create_table('ai_extraction_rules',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('strategy_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('extraction_method', postgresql.ENUM('llm', 'regex', 'ner', 'hybrid', name='extractionmethod'), autoincrement=False, nullable=False),
    sa.Column('pattern', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('validation_rules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('trigger_conditions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['chat_strategies.id'], name=op.f('ai_extraction_rules_strategy_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_extraction_rules_pkey'))
    )
    op.create_index(op.f('ix_ai_extraction_rules_strategy_id'), 'ai_extraction_rules', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_ai_extraction_rules_entity_type'), 'ai_extraction_rules', ['entity_type'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='patients_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='patients_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('risk_assessments',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('assessment_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('risk_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('risk_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('assessed_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], name=op.f('risk_assessments_assessed_by_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('risk_assessments_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('risk_assessments_pkey'))
    )
    op.create_table('ai_session_analytics',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('total_messages', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('conversation_duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completion_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('extraction_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('patient_satisfaction_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ai_confidence_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('criteria_met', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('recommendations_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_chat_sessions.id'], name=op.f('ai_session_analytics_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_session_analytics_pkey'))
    )
    op.create_index(op.f('ix_ai_session_analytics_session_id'), 'ai_session_analytics', ['session_id'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('invite_token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('clinician_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('custom_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('accepted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], name=op.f('invites_clinician_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('invites_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('invites_pkey'))
    )
    op.create_index(op.f('idx_invites_email'), 'invites', ['email'], unique=False)
    op.create_table('lab_results',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('lab_order_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('test_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('result_value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reference_range', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'final'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lab_order_id'], ['lab_orders.id'], name=op.f('lab_results_lab_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lab_results_pkey'))
    )
    op.create_table('ai_chat_messages',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('user', 'assistant', 'system', name='messagerole'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message_type', postgresql.ENUM('question', 'response', 'summary', 'assessment', 'clarification', name='messagetype'), autoincrement=False, nullable=False),
    sa.Column('prompt_template', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rag_sources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('extracted_entities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('extracted_intent', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('processing_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_chat_sessions.id'], name=op.f('ai_chat_messages_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_chat_messages_pkey'))
    )
    op.create_index(op.f('ix_ai_chat_messages_session_id'), 'ai_chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_chat_messages_role'), 'ai_chat_messages', ['role'], unique=False)
    op.create_index(op.f('ix_ai_chat_messages_created_at'), 'ai_chat_messages', ['created_at'], unique=False)
    op.create_table('targeting_rules',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('strategy_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('field', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('operator', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('sequence', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['chat_strategies.id'], name=op.f('targeting_rules_strategy_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('targeting_rules_pkey'))
    )
    op.create_table('chat_strategies',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('goal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('patient_introduction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('specialty', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='fk_chat_strategies_account'),
    sa.PrimaryKeyConstraint('id', name='chat_strategies_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('lab_orders',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('order_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('lab_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ordered_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ordered_by'], ['users.id'], name=op.f('lab_orders_ordered_by_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('lab_orders_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lab_orders_pkey'))
    )
    op.create_table('strategy_knowledge_sources',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('strategy_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('knowledge_source_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['knowledge_source_id'], ['knowledge_sources.id'], name=op.f('strategy_knowledge_sources_knowledge_source_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['chat_strategies.id'], name=op.f('strategy_knowledge_sources_strategy_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('strategy_knowledge_sources_pkey')),
    sa.UniqueConstraint('strategy_id', 'knowledge_source_id', name=op.f('strategy_knowledge_sources_strategy_id_knowledge_source_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('accounts',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='accounts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('knowledge_sources',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processing_status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_knowledge_sources_account')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('knowledge_sources_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_sources_pkey'))
    )
    op.create_table('ai_chat_sessions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('strategy_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('session_type', postgresql.ENUM('screening', 'assessment', 'follow_up', 'consultation', name='sessiontype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'completed', 'paused', 'error', 'cancelled', name='sessionstatus'), autoincrement=False, nullable=False),
    sa.Column('chat_context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('extracted_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('assessment_results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('strategy_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_activity', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('ai_chat_sessions_patient_id_fkey')),
    sa.ForeignKeyConstraint(['strategy_id'], ['chat_strategies.id'], name=op.f('ai_chat_sessions_strategy_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_chat_sessions_pkey'))
    )
    op.create_index(op.f('ix_ai_chat_sessions_strategy_id'), 'ai_chat_sessions', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_ai_chat_sessions_status'), 'ai_chat_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_ai_chat_sessions_started_at'), 'ai_chat_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_ai_chat_sessions_patient_id'), 'ai_chat_sessions', ['patient_id'], unique=False)
    # ### end Alembic commands ###
