"""finalize_chat_configuration_schema_cleanup

Revision ID: ce2d20f7e4be
Revises: 300453bc4cec
Create Date: 2025-06-23 08:52:09.083038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce2d20f7e4be'
down_revision: Union[str, None] = '300453bc4cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinician_availability',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clinician_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinician_availability_clinician_id'), 'clinician_availability', ['clinician_id'], unique=False)
    op.create_table('lab_integrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lab_name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('api_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('medical_history', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('eligibility_results')
    op.alter_column('accounts', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('accounts', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'suspended', name='account_status'),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::account_status"))
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.alter_column('appointments', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('appointments', 'clinician_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('appointments', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('appointments', 'appointment_type',
               existing_type=postgresql.ENUM('virtual', 'in_person', name='appointment_type'),
               type_=sa.String(length=20),
               nullable=True)
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('scheduled', 'completed', 'cancelled', 'no_show', name='appointment_status'),
               type_=sa.String(length=20),
               nullable=True,
               existing_server_default=sa.text("'scheduled'::appointment_status"))
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('appointments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_appointments_clinician_id'), table_name='appointments')
    op.drop_index(op.f('idx_appointments_patient_id'), table_name='appointments')
    op.create_index(op.f('ix_appointments_clinician_id'), 'appointments', ['clinician_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.drop_constraint(op.f('appointments_patient_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'duration_minutes')
    op.add_column('chat_answers', sa.Column('answer_value', sa.JSON(), nullable=True))
    op.alter_column('chat_answers', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('chat_answers', 'session_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('chat_answers', 'question_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('chat_answers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_answers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_chat_answers_session_id'), table_name='chat_answers')
    op.add_column('chat_questions', sa.Column('sequence', sa.Integer(), nullable=False))
    op.add_column('chat_questions', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('chat_questions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('chat_questions', sa.Column('answer_type', sa.String(), nullable=False))
    op.add_column('chat_questions', sa.Column('required', sa.Boolean(), nullable=True))
    op.add_column('chat_questions', sa.Column('category', sa.String(), nullable=True))
    op.add_column('chat_questions', sa.Column('strategy_id', sa.String(), nullable=True))
    op.add_column('chat_questions', sa.Column('knowledge_source_id', sa.String(), nullable=True))
    op.add_column('chat_questions', sa.Column('is_dynamic', sa.Boolean(), nullable=False))
    op.add_column('chat_questions', sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('chat_questions', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('chat_questions', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('chat_questions', 'next_question_logic',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('chat_questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_questions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_foreign_key(None, 'chat_questions', 'knowledge_sources', ['knowledge_source_id'], ['id'])
    op.create_foreign_key(None, 'chat_questions', 'chat_strategies', ['strategy_id'], ['id'])
    op.drop_column('chat_questions', 'order_index')
    op.drop_column('chat_questions', 'question_type')
    op.drop_column('chat_questions', 'is_required')
    op.drop_column('chat_questions', 'question_text')
    op.add_column('chat_sessions', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('session_metadata', sa.JSON(), nullable=True))
    op.add_column('chat_sessions', sa.Column('strategy_id', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('strategy_execution_id', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('triggered_by_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chat_sessions', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('chat_sessions', 'patient_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'clinician_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'session_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('chat_sessions', 'status',
               existing_type=postgresql.ENUM('in_progress', 'completed', 'abandoned', name='chat_session_status'),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'in_progress'::chat_session_status"))
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_chat_sessions_patient_id'), table_name='chat_sessions')
    op.drop_constraint(op.f('chat_sessions_patient_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'strategy_executions', ['strategy_execution_id'], ['id'])
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'chat_sessions', 'users', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'chat_sessions', 'chat_strategies', ['strategy_id'], ['id'])
    op.alter_column('chat_strategies', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('chat_strategies', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('chat_strategies', 'account_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('chat_strategies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('chat_strategies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('idx_chat_strategies_account_id'), table_name='chat_strategies')
    op.drop_index(op.f('idx_chat_strategies_created_by'), table_name='chat_strategies')
    op.drop_constraint(op.f('chat_strategies_account_id_fkey'), 'chat_strategies', type_='foreignkey')
    op.create_foreign_key(None, 'chat_strategies', 'accounts', ['account_id'], ['id'])
    op.alter_column('invites', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('invites', 'provider_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('invites', 'patient_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('invites', 'clinician_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('invites', 'status',
               existing_type=postgresql.ENUM('pending', 'completed', 'expired', name='invite_status'),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::invite_status"))
    op.alter_column('invites', 'session_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('invites', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('invites', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('idx_invites_email'), table_name='invites')
    op.create_index(op.f('ix_invites_email'), 'invites', ['email'], unique=False)
    op.create_foreign_key(None, 'invites', 'users', ['clinician_id'], ['id'])
    op.alter_column('knowledge_sources', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('knowledge_sources', 'file_size',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('knowledge_sources', 'account_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('knowledge_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('knowledge_sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('idx_knowledge_sources_account_id'), table_name='knowledge_sources')
    op.drop_index(op.f('idx_knowledge_sources_created_by'), table_name='knowledge_sources')
    op.drop_index(op.f('idx_knowledge_sources_status'), table_name='knowledge_sources')
    op.drop_index(op.f('idx_knowledge_sources_type'), table_name='knowledge_sources')
    op.drop_constraint(op.f('knowledge_sources_account_id_fkey'), 'knowledge_sources', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_sources', 'accounts', ['account_id'], ['id'])
    op.add_column('lab_orders', sa.Column('clinician_id', sa.String(), nullable=False))
    op.add_column('lab_orders', sa.Column('lab_id', sa.String(), nullable=True))
    op.add_column('lab_orders', sa.Column('external_order_id', sa.String(), nullable=True))
    op.add_column('lab_orders', sa.Column('order_number', sa.String(), nullable=False))
    op.add_column('lab_orders', sa.Column('test_type', sa.String(), nullable=False))
    op.add_column('lab_orders', sa.Column('requisition_details', sa.JSON(), nullable=True))
    op.add_column('lab_orders', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('lab_orders', sa.Column('collection_date', sa.DateTime(), nullable=True))
    op.add_column('lab_orders', sa.Column('completed_date', sa.DateTime(), nullable=True))
    op.alter_column('lab_orders', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('lab_orders', 'patient_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('lab_orders', 'status',
               existing_type=postgresql.ENUM('ordered', 'processing', 'completed', 'cancelled', name='lab_order_status'),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'ordered'::lab_order_status"))
    op.alter_column('lab_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('lab_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_lab_orders_patient_id'), table_name='lab_orders')
    op.create_unique_constraint(None, 'lab_orders', ['order_number'])
    op.drop_constraint(op.f('lab_orders_patient_id_fkey'), 'lab_orders', type_='foreignkey')
    op.drop_constraint(op.f('lab_orders_provider_id_fkey'), 'lab_orders', type_='foreignkey')
    op.drop_constraint(op.f('lab_orders_eligibility_result_id_fkey'), 'lab_orders', type_='foreignkey')
    op.create_foreign_key(None, 'lab_orders', 'lab_integrations', ['lab_id'], ['id'])
    op.create_foreign_key(None, 'lab_orders', 'users', ['clinician_id'], ['id'])
    op.create_foreign_key(None, 'lab_orders', 'users', ['patient_id'], ['id'])
    op.drop_column('lab_orders', 'provider_id')
    op.drop_column('lab_orders', 'ordered_tests')
    op.drop_column('lab_orders', 'insurance_information')
    op.drop_column('lab_orders', 'eligibility_result_id')
    op.drop_column('lab_orders', 'lab_api_order_id')
    op.add_column('lab_results', sa.Column('result_status', sa.String(), nullable=False))
    op.add_column('lab_results', sa.Column('report_url', sa.String(), nullable=True))
    op.add_column('lab_results', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('lab_results', sa.Column('abnormal', sa.Boolean(), nullable=True))
    op.add_column('lab_results', sa.Column('reviewed', sa.Boolean(), nullable=True))
    op.alter_column('lab_results', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('lab_results', 'order_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('lab_results', 'result_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('lab_results', 'reviewed_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('lab_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('lab_results', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_lab_results_order_id'), table_name='lab_results')
    op.drop_column('lab_results', 'lab_api_result_id')
    op.drop_column('lab_results', 'status')
    op.alter_column('outcome_actions', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('outcome_actions', 'strategy_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('outcome_actions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('outcome_actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('idx_outcome_actions_strategy_id'), table_name='outcome_actions')
    op.alter_column('patients', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('patients', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('patients', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('patients', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'archived', name='patient_status'),
               type_=sa.String(),
               nullable=True,
               existing_server_default=sa.text("'active'::patient_status"))
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('patients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('patients', 'clinician_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('patients', 'account_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('patients', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_patients_clinician_id'), table_name='patients')
    op.drop_index(op.f('idx_patients_external_id'), table_name='patients')
    op.drop_index(op.f('idx_patients_user_id'), table_name='patients')
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=False)
    op.create_index(op.f('ix_patients_external_id'), 'patients', ['external_id'], unique=False)
    op.create_unique_constraint(None, 'patients', ['user_id'])
    op.add_column('recurring_availability', sa.Column('day_of_week', sa.Integer(), nullable=False))
    op.add_column('recurring_availability', sa.Column('time', sa.Time(), nullable=False))
    op.add_column('recurring_availability', sa.Column('valid_until', sa.Date(), nullable=True))
    op.alter_column('recurring_availability', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('recurring_availability', 'clinician_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('recurring_availability', 'days_of_week',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('recurring_availability', 'time_slots',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('recurring_availability', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('recurring_availability', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_recurring_availability_clinician_id'), 'recurring_availability', ['clinician_id'], unique=False)
    op.drop_constraint(op.f('recurring_availability_clinician_id_fkey'), 'recurring_availability', type_='foreignkey')
    op.add_column('risk_assessments', sa.Column('is_eligible', sa.Boolean(), nullable=False))
    op.add_column('risk_assessments', sa.Column('nccn_eligible', sa.Boolean(), nullable=False))
    op.add_column('risk_assessments', sa.Column('tyrer_cuzick_score', sa.Integer(), nullable=True))
    op.add_column('risk_assessments', sa.Column('tyrer_cuzick_threshold', sa.Integer(), nullable=True))
    op.add_column('risk_assessments', sa.Column('risk_factors', sa.JSON(), nullable=True))
    op.alter_column('risk_assessments', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('risk_assessments', 'patient_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('risk_assessments', 'session_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('risk_assessments', 'recommendations',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('risk_assessments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('risk_assessments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('risk_assessments_patient_id_fkey'), 'risk_assessments', type_='foreignkey')
    op.create_foreign_key(None, 'risk_assessments', 'users', ['patient_id'], ['id'])
    op.drop_column('risk_assessments', 'risk_level')
    op.drop_column('risk_assessments', 'factors')
    op.drop_column('risk_assessments', 'risk_score')
    op.add_column('strategy_analytics', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('strategy_analytics', sa.Column('patients_screened', sa.Integer(), nullable=False))
    op.add_column('strategy_analytics', sa.Column('criteria_met', sa.Integer(), nullable=False))
    op.add_column('strategy_analytics', sa.Column('criteria_not_met', sa.Integer(), nullable=False))
    op.add_column('strategy_analytics', sa.Column('incomplete_data', sa.Integer(), nullable=False))
    op.add_column('strategy_analytics', sa.Column('avg_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('strategy_analytics', sa.Column('tasks_created', sa.Integer(), nullable=False))
    op.add_column('strategy_analytics', sa.Column('charts_flagged', sa.Integer(), nullable=False))
    op.add_column('strategy_analytics', sa.Column('messages_sent', sa.Integer(), nullable=False))
    op.add_column('strategy_analytics', sa.Column('followups_scheduled', sa.Integer(), nullable=False))
    op.alter_column('strategy_analytics', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('strategy_analytics', 'strategy_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('strategy_analytics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('idx_strategy_analytics_metric'), table_name='strategy_analytics')
    op.drop_index(op.f('idx_strategy_analytics_strategy_id'), table_name='strategy_analytics')
    op.drop_index(op.f('idx_strategy_analytics_time'), table_name='strategy_analytics')
    op.create_unique_constraint(None, 'strategy_analytics', ['strategy_id', 'date'])
    op.drop_constraint(op.f('strategy_analytics_strategy_id_fkey'), 'strategy_analytics', type_='foreignkey')
    op.create_foreign_key(None, 'strategy_analytics', 'chat_strategies', ['strategy_id'], ['id'])
    op.drop_column('strategy_analytics', 'metric_name')
    op.drop_column('strategy_analytics', 'time_period')
    op.drop_column('strategy_analytics', 'metric_value')
    op.drop_column('strategy_analytics', 'dimension_filters')
    op.drop_column('strategy_analytics', 'recorded_at')
    op.add_column('strategy_executions', sa.Column('patient_id', sa.String(), nullable=False))
    op.add_column('strategy_executions', sa.Column('triggered_by', sa.String(), nullable=True))
    op.add_column('strategy_executions', sa.Column('trigger_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('strategy_executions', sa.Column('execution_status', sa.String(), nullable=False))
    op.add_column('strategy_executions', sa.Column('outcome_result', sa.String(), nullable=True))
    op.add_column('strategy_executions', sa.Column('executed_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('strategy_executions', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('strategy_executions', 'strategy_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('strategy_executions', 'session_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('strategy_executions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('strategy_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('idx_strategy_executions_session_id'), table_name='strategy_executions')
    op.drop_index(op.f('idx_strategy_executions_status'), table_name='strategy_executions')
    op.drop_index(op.f('idx_strategy_executions_strategy_id'), table_name='strategy_executions')
    op.drop_index(op.f('idx_strategy_executions_user_id'), table_name='strategy_executions')
    op.drop_constraint(op.f('strategy_executions_strategy_id_fkey'), 'strategy_executions', type_='foreignkey')
    op.drop_constraint(op.f('strategy_executions_session_id_fkey'), 'strategy_executions', type_='foreignkey')
    op.drop_constraint(op.f('strategy_executions_user_id_fkey'), 'strategy_executions', type_='foreignkey')
    op.create_foreign_key(None, 'strategy_executions', 'chat_sessions', ['session_id'], ['id'])
    op.create_foreign_key(None, 'strategy_executions', 'users', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'strategy_executions', 'users', ['triggered_by'], ['id'])
    op.create_foreign_key(None, 'strategy_executions', 'chat_strategies', ['strategy_id'], ['id'])
    op.drop_column('strategy_executions', 'results')
    op.drop_column('strategy_executions', 'user_id')
    op.drop_column('strategy_executions', 'execution_context')
    op.drop_column('strategy_executions', 'status')
    op.alter_column('strategy_knowledge_sources', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('strategy_knowledge_sources', 'strategy_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('strategy_knowledge_sources', 'knowledge_source_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('strategy_knowledge_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('idx_strategy_knowledge_source_id'), table_name='strategy_knowledge_sources')
    op.drop_index(op.f('idx_strategy_knowledge_strategy_id'), table_name='strategy_knowledge_sources')
    op.alter_column('targeting_rules', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('targeting_rules', 'strategy_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('targeting_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('targeting_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('idx_targeting_rules_strategy_id'), table_name='targeting_rules')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('patient', 'clinician', 'admin', 'super_admin', 'lab_tech', name='user_role'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'account_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'clinician_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_users_account_id'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', postgresql.ENUM('active', 'inactive', 'invited', 'suspended', name='user_status'), server_default=sa.text("'active'::user_status"), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_account_id'), 'users', ['account_id'], unique=False)
    op.alter_column('users', 'clinician_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'account_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('patient', 'clinician', 'admin', 'super_admin', 'lab_tech', name='user_role'),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.create_index(op.f('idx_targeting_rules_strategy_id'), 'targeting_rules', ['strategy_id'], unique=False)
    op.alter_column('targeting_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('targeting_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('targeting_rules', 'strategy_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('targeting_rules', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_index(op.f('idx_strategy_knowledge_strategy_id'), 'strategy_knowledge_sources', ['strategy_id'], unique=False)
    op.create_index(op.f('idx_strategy_knowledge_source_id'), 'strategy_knowledge_sources', ['knowledge_source_id'], unique=False)
    op.alter_column('strategy_knowledge_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('strategy_knowledge_sources', 'knowledge_source_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('strategy_knowledge_sources', 'strategy_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('strategy_knowledge_sources', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('strategy_executions', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('strategy_executions', sa.Column('execution_context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('strategy_executions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('strategy_executions', sa.Column('results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'strategy_executions', type_='foreignkey')
    op.drop_constraint(None, 'strategy_executions', type_='foreignkey')
    op.drop_constraint(None, 'strategy_executions', type_='foreignkey')
    op.drop_constraint(None, 'strategy_executions', type_='foreignkey')
    op.create_foreign_key(op.f('strategy_executions_user_id_fkey'), 'strategy_executions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('strategy_executions_session_id_fkey'), 'strategy_executions', 'chat_sessions', ['session_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('strategy_executions_strategy_id_fkey'), 'strategy_executions', 'chat_strategies', ['strategy_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_strategy_executions_user_id'), 'strategy_executions', ['user_id'], unique=False)
    op.create_index(op.f('idx_strategy_executions_strategy_id'), 'strategy_executions', ['strategy_id'], unique=False)
    op.create_index(op.f('idx_strategy_executions_status'), 'strategy_executions', ['status'], unique=False)
    op.create_index(op.f('idx_strategy_executions_session_id'), 'strategy_executions', ['session_id'], unique=False)
    op.alter_column('strategy_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('strategy_executions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('strategy_executions', 'session_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('strategy_executions', 'strategy_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('strategy_executions', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('strategy_executions', 'executed_actions')
    op.drop_column('strategy_executions', 'outcome_result')
    op.drop_column('strategy_executions', 'execution_status')
    op.drop_column('strategy_executions', 'trigger_criteria')
    op.drop_column('strategy_executions', 'triggered_by')
    op.drop_column('strategy_executions', 'patient_id')
    op.add_column('strategy_analytics', sa.Column('recorded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('strategy_analytics', sa.Column('dimension_filters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('strategy_analytics', sa.Column('metric_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('strategy_analytics', sa.Column('time_period', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('strategy_analytics', sa.Column('metric_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'strategy_analytics', type_='foreignkey')
    op.create_foreign_key(op.f('strategy_analytics_strategy_id_fkey'), 'strategy_analytics', 'chat_strategies', ['strategy_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'strategy_analytics', type_='unique')
    op.create_index(op.f('idx_strategy_analytics_time'), 'strategy_analytics', ['time_period', 'recorded_at'], unique=False)
    op.create_index(op.f('idx_strategy_analytics_strategy_id'), 'strategy_analytics', ['strategy_id'], unique=False)
    op.create_index(op.f('idx_strategy_analytics_metric'), 'strategy_analytics', ['metric_name'], unique=False)
    op.alter_column('strategy_analytics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('strategy_analytics', 'strategy_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('strategy_analytics', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('strategy_analytics', 'followups_scheduled')
    op.drop_column('strategy_analytics', 'messages_sent')
    op.drop_column('strategy_analytics', 'charts_flagged')
    op.drop_column('strategy_analytics', 'tasks_created')
    op.drop_column('strategy_analytics', 'avg_duration_minutes')
    op.drop_column('strategy_analytics', 'incomplete_data')
    op.drop_column('strategy_analytics', 'criteria_not_met')
    op.drop_column('strategy_analytics', 'criteria_met')
    op.drop_column('strategy_analytics', 'patients_screened')
    op.drop_column('strategy_analytics', 'date')
    op.add_column('risk_assessments', sa.Column('risk_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('risk_assessments', sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('risk_assessments', sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'risk_assessments', type_='foreignkey')
    op.create_foreign_key(op.f('risk_assessments_patient_id_fkey'), 'risk_assessments', 'patients', ['patient_id'], ['id'])
    op.alter_column('risk_assessments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('risk_assessments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('risk_assessments', 'recommendations',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('risk_assessments', 'session_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               nullable=True)
    op.alter_column('risk_assessments', 'patient_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               nullable=True)
    op.alter_column('risk_assessments', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.drop_column('risk_assessments', 'risk_factors')
    op.drop_column('risk_assessments', 'tyrer_cuzick_threshold')
    op.drop_column('risk_assessments', 'tyrer_cuzick_score')
    op.drop_column('risk_assessments', 'nccn_eligible')
    op.drop_column('risk_assessments', 'is_eligible')
    op.create_foreign_key(op.f('recurring_availability_clinician_id_fkey'), 'recurring_availability', 'users', ['clinician_id'], ['id'])
    op.drop_index(op.f('ix_recurring_availability_clinician_id'), table_name='recurring_availability')
    op.alter_column('recurring_availability', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('recurring_availability', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('recurring_availability', 'time_slots',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('recurring_availability', 'days_of_week',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('recurring_availability', 'clinician_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('recurring_availability', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.drop_column('recurring_availability', 'valid_until')
    op.drop_column('recurring_availability', 'time')
    op.drop_column('recurring_availability', 'day_of_week')
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_index(op.f('ix_patients_external_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.create_index(op.f('idx_patients_user_id'), 'patients', ['user_id'], unique=False)
    op.create_index(op.f('idx_patients_external_id'), 'patients', ['external_id'], unique=False)
    op.create_index(op.f('idx_patients_clinician_id'), 'patients', ['clinician_id'], unique=False)
    op.alter_column('patients', 'user_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('patients', 'account_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('patients', 'clinician_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('patients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('patients', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('active', 'inactive', 'archived', name='patient_status'),
               nullable=False,
               existing_server_default=sa.text("'active'::patient_status"))
    op.alter_column('patients', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('patients', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('patients', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.create_index(op.f('idx_outcome_actions_strategy_id'), 'outcome_actions', ['strategy_id'], unique=False)
    op.alter_column('outcome_actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('outcome_actions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('outcome_actions', 'strategy_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('outcome_actions', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('lab_results', sa.Column('status', postgresql.ENUM('pending', 'available', 'reviewed', name='lab_result_status'), server_default=sa.text("'pending'::lab_result_status"), autoincrement=False, nullable=False))
    op.add_column('lab_results', sa.Column('lab_api_result_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_lab_results_order_id'), 'lab_results', ['order_id'], unique=False)
    op.alter_column('lab_results', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('lab_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('lab_results', 'reviewed_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('lab_results', 'result_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('lab_results', 'order_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               nullable=True)
    op.alter_column('lab_results', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.drop_column('lab_results', 'reviewed')
    op.drop_column('lab_results', 'abnormal')
    op.drop_column('lab_results', 'summary')
    op.drop_column('lab_results', 'report_url')
    op.drop_column('lab_results', 'result_status')
    op.add_column('lab_orders', sa.Column('lab_api_order_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('lab_orders', sa.Column('eligibility_result_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('lab_orders', sa.Column('insurance_information', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('lab_orders', sa.Column('ordered_tests', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('lab_orders', sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lab_orders', type_='foreignkey')
    op.drop_constraint(None, 'lab_orders', type_='foreignkey')
    op.drop_constraint(None, 'lab_orders', type_='foreignkey')
    op.create_foreign_key(op.f('lab_orders_eligibility_result_id_fkey'), 'lab_orders', 'eligibility_results', ['eligibility_result_id'], ['id'])
    op.create_foreign_key(op.f('lab_orders_provider_id_fkey'), 'lab_orders', 'users', ['provider_id'], ['id'])
    op.create_foreign_key(op.f('lab_orders_patient_id_fkey'), 'lab_orders', 'patients', ['patient_id'], ['id'])
    op.drop_constraint(None, 'lab_orders', type_='unique')
    op.create_index(op.f('idx_lab_orders_patient_id'), 'lab_orders', ['patient_id'], unique=False)
    op.alter_column('lab_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('lab_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('lab_orders', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ordered', 'processing', 'completed', 'cancelled', name='lab_order_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'ordered'::lab_order_status"))
    op.alter_column('lab_orders', 'patient_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               nullable=True)
    op.alter_column('lab_orders', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.drop_column('lab_orders', 'completed_date')
    op.drop_column('lab_orders', 'collection_date')
    op.drop_column('lab_orders', 'notes')
    op.drop_column('lab_orders', 'requisition_details')
    op.drop_column('lab_orders', 'test_type')
    op.drop_column('lab_orders', 'order_number')
    op.drop_column('lab_orders', 'external_order_id')
    op.drop_column('lab_orders', 'lab_id')
    op.drop_column('lab_orders', 'clinician_id')
    op.drop_constraint(None, 'knowledge_sources', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_sources_account_id_fkey'), 'knowledge_sources', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_knowledge_sources_type'), 'knowledge_sources', ['source_type'], unique=False)
    op.create_index(op.f('idx_knowledge_sources_status'), 'knowledge_sources', ['processing_status'], unique=False)
    op.create_index(op.f('idx_knowledge_sources_created_by'), 'knowledge_sources', ['created_by'], unique=False)
    op.create_index(op.f('idx_knowledge_sources_account_id'), 'knowledge_sources', ['account_id'], unique=False)
    op.alter_column('knowledge_sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('knowledge_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('knowledge_sources', 'account_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('knowledge_sources', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('knowledge_sources', 'file_size',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.drop_index(op.f('ix_invites_email'), table_name='invites')
    op.create_index(op.f('idx_invites_email'), 'invites', ['email'], unique=False)
    op.alter_column('invites', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('invites', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('invites', 'session_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('invites', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('pending', 'completed', 'expired', name='invite_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::invite_status"))
    op.alter_column('invites', 'clinician_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('invites', 'patient_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               nullable=True)
    op.alter_column('invites', 'provider_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('invites', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.drop_constraint(None, 'chat_strategies', type_='foreignkey')
    op.create_foreign_key(op.f('chat_strategies_account_id_fkey'), 'chat_strategies', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_chat_strategies_created_by'), 'chat_strategies', ['created_by'], unique=False)
    op.create_index(op.f('idx_chat_strategies_account_id'), 'chat_strategies', ['account_id'], unique=False)
    op.alter_column('chat_strategies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('chat_strategies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('chat_strategies', 'account_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('chat_strategies', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('chat_strategies', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('chat_sessions_patient_id_fkey'), 'chat_sessions', 'patients', ['patient_id'], ['id'])
    op.create_index(op.f('idx_chat_sessions_patient_id'), 'chat_sessions', ['patient_id'], unique=False)
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_sessions', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('in_progress', 'completed', 'abandoned', name='chat_session_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'in_progress'::chat_session_status"))
    op.alter_column('chat_sessions', 'session_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('chat_sessions', 'clinician_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'patient_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.drop_column('chat_sessions', 'completed_at')
    op.drop_column('chat_sessions', 'triggered_by_rules')
    op.drop_column('chat_sessions', 'strategy_execution_id')
    op.drop_column('chat_sessions', 'strategy_id')
    op.drop_column('chat_sessions', 'session_metadata')
    op.drop_column('chat_sessions', 'user_id')
    op.add_column('chat_questions', sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('chat_questions', sa.Column('is_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('chat_questions', sa.Column('question_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('chat_questions', sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_questions', type_='foreignkey')
    op.drop_constraint(None, 'chat_questions', type_='foreignkey')
    op.alter_column('chat_questions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_questions', 'next_question_logic',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('chat_questions', 'options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('chat_questions', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.drop_column('chat_questions', 'context')
    op.drop_column('chat_questions', 'is_dynamic')
    op.drop_column('chat_questions', 'knowledge_source_id')
    op.drop_column('chat_questions', 'strategy_id')
    op.drop_column('chat_questions', 'category')
    op.drop_column('chat_questions', 'required')
    op.drop_column('chat_questions', 'answer_type')
    op.drop_column('chat_questions', 'description')
    op.drop_column('chat_questions', 'text')
    op.drop_column('chat_questions', 'sequence')
    op.create_index(op.f('idx_chat_answers_session_id'), 'chat_answers', ['session_id'], unique=False)
    op.alter_column('chat_answers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_answers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_answers', 'question_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               nullable=True)
    op.alter_column('chat_answers', 'session_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               nullable=True)
    op.alter_column('chat_answers', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.drop_column('chat_answers', 'answer_value')
    op.add_column('appointments', sa.Column('duration_minutes', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('appointments_patient_id_fkey'), 'appointments', 'patients', ['patient_id'], ['id'])
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_clinician_id'), table_name='appointments')
    op.create_index(op.f('idx_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('idx_appointments_clinician_id'), 'appointments', ['clinician_id'], unique=False)
    op.alter_column('appointments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('appointments', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('scheduled', 'completed', 'cancelled', 'no_show', name='appointment_status'),
               nullable=False,
               existing_server_default=sa.text("'scheduled'::appointment_status"))
    op.alter_column('appointments', 'appointment_type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('virtual', 'in_person', name='appointment_type'),
               nullable=False)
    op.alter_column('appointments', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('appointments', 'clinician_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('appointments', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.alter_column('accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('accounts', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('active', 'inactive', 'suspended', name='account_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::account_status"))
    op.alter_column('accounts', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.create_table('eligibility_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_eligible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('eligibility_results_patient_id_fkey')),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name=op.f('eligibility_results_provider_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('eligibility_results_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('eligibility_results_pkey'))
    )
    op.drop_table('patient_profiles')
    op.drop_table('lab_integrations')
    op.drop_index(op.f('ix_clinician_availability_clinician_id'), table_name='clinician_availability')
    op.drop_table('clinician_availability')
    # ### end Alembic commands ###
